# Read the Docs configuration file (v2)
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

# Build documentation with Sphinx
sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

# Build formats
formats:
  - pdf
  - epub

# Build environment
build:
  os: ubuntu-22.04
  tools:
    python: "3.13"
  jobs:
    post_install:
      - pip install -r docs/requirements.txt